apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-frontend
  labels:
    app: VueApp
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: VueApp
      tier: frontend
  template:
    metadata:
      labels:
        app: VueApp
        tier: frontend
    spec:
      containers:
      - name: vue-frontend
        image: vue-frontend:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: vue-frontend-service
  labels:
    app: VueApp
    tier: frontend
spec:
  selector:
    app: VueApp
    tier: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
