apiVersion: apps/v1
kind: Deployment
metadata:
  name: netapp
  labels:
    app: NetApp
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: NetApp
      tier: backend
  template:
    metadata:
      labels:
        app: NetApp
        tier: backend
    spec:
      containers:
      - name: netapp
        image: my-dotnet-api:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 256Mi
            cpu: 200m
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        # === ConfigMap ===
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: Host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: Port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: Database
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: Username

        # === Secret ===
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: Password
---
apiVersion: v1
kind: Service
metadata:
  name: netapp-service
  labels:
    app: NetApp
    tier: backend
spec:
  selector:
    app: NetApp
    tier: backend
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
